### ISSUE TITLE
Allow Pipeline deletion

### ISSUE THREAD

**Issue by darkcrux** [AcalephStorage/kontinuous#28]
It should be possible to delete a pipeline (repository). Useful for cleanup especially when building for a specific repository is no longer needed.

**Comment by hunter** [comment]
This should also clean up all builds and associated data.

**Comment by madziefe** [comment]
added delete pipeline for api request.
should we also use the same ticket for the delete in kontinuous-cli?

**Comment by hunter** [comment]
Yeah, keep it open for the CLI

**Comment by madziefe** [comment]
Done with cli. 
delete pipeline
  kontinuous-cli delete pipeline <pipeline-name>

delete build #29 
  kontinuous-cli delete build <pipeline-name> -build <build number>
