### ISSUE TITLE
Update kontinuous-deploy for UI

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous#38]
With the v0.1.2 release we've added support for Github Auth and also added a web based UI. `kontinuous-deploy` needs to be updated to support these new features.

**Comment by madziefe** [comment]
added --clientid in kontinuous-cli deploy for github client id.

**Comment by hunter** [comment]
@madziefe can this be closed?

**Comment by madziefe** [comment]
yes @hunter. deploy is now in kontinuous-cli and it supports github auth.
