### ISSUE TITLE
Improve on-boarding experience

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous#39]
`kontinuous-deploy` is a handy tool for getting people started but I think there can be improvements to make it even easier. Following some discussions on combining the CLI and deploy, I'm thinking we might be able to do a workflow as follows:
# Download/Install CLI (homebrew and/or curl example)
# `kontinuous-cli deploy` with install args (or prompt for the params) which launches Kontinous in the cluster
# `kontinuous-cli init` to add an example .pipeline.yml to a repo
# Commit code
# `kontinuous-cli create pipeline` (which will trigger the initial build)
# `kontinuous-cli get pipelines` to view all pipelines
# `kontinuous-cli describe pipelines my-pipeline` to view latest build

**Comment by madziefe** [comment]
done with kontinuous-deploy with ui resource  and github support included.

**Comment by darkcrux** [comment]
I think we can close this.
