### ISSUE TITLE
Ensure secrets like GithubClientSecrets are not passed as environment variables to Kontinuous

### ISSUE THREAD

**Issue by darkcrux** [AcalephStorage/kontinuous#40]
sensitive data should not be passed to kontinuous via Environment variables. these can be added through k8s secrets instead.

**Comment by madziefe** [comment]
Supported in release 0.1.3. GithubClientID and GithubClientSecret are part of kontinuous-secrets

**Comment by darkcrux** [comment]
closing this. :)
