### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/kontinuous#59]
Since we're handling credentials, SSL will need to be enabled (ideally with HTTP/2)

**Comment by darkcrux** [comment]
PR #61 fixes this.

**Comment by madziefe** [comment]
#61Added ssl support  in  `kontinuous-cli deploy`

**Comment by madziefe** [comment]
Changes:
1. Kontinuous api and dashboard as containers in one deployment and service resource. 
2. `kontinuous-cli deploy.` Generate ssl certs and keys for kontinuous api and dashboard.
